apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: username/myapp:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
            - name: DB_NAME
              value: "mydb"
